### ISSUE TITLE
Capybara error

### ISSUE THREAD

**Issue by aenser** [learn-co-curriculum/lazy-loader.js#7]
I kept getting this error when I ran my tests:

`/lazy-loader.js-v-000/spec/spec_helper.rb:11:in `block in <top (required)>': uninitialized constant Capybara::DSL (NameError)`

I tried reinstalling and updating my gems, but no success in getting Capybara to work.
All of my code is working in the browser when I run shotgun, but I couldn't get my rspec tests to pass. I submitted the code anyways since it's working, but I figured I would raise this issue. 

Thanks,
Aaron

**Comment by AnnJohn** [comment]
Thanks @aenser will look into this soon

**Comment by pletcher** [comment]
Hi @aenser, if you add

```ruby
require 'capybara/rspec'
```
after `require capybara` in spec/spec_helper.rb, your tests should run.

This was updated a while ago on our end, but it looks like you might have gotten stuck with an older fork. Sorry about that!
